[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
packet = {version = "0.1.0", path = "../packet"}
protocol_spec = { version = "0.1.0", path = "../protocol_spec" }
bytel = { version = "0.1.0", path="../bytel" }